### ISSUE TITLE
How to download a file using a chrome browser without opening download file dialog box

### ISSUE THREAD

**Issue by PingleSneha** [aerokube/selenoid-images#130] opened 2019-05-15 06:43 UTC
Hi. I am trying to download a file and verify its contents using chrome browser. Below are my chrome options i am trying to use, with these options the download file dialog box opens and my test script fails. I am looking out for chrome and firefox options to suppress download file dialog box and proceed with file download.

ChromeOptions - 

String path = "home" + File.separator + "selenium" + File.separator + "Downloads" + File.separator;
		System.setProperty("webdriver.chrome.driver", System.getProperty("user.dir") + File.separator + "lib" + File.separator + "chromedriver.exe");
		System.setProperty("webdriver.chrome.verboseLogging", "true");
		System.setProperty(ChromeDriverService.CHROME_DRIVER_LOG_PROPERTY,
				System.getProperty("user.dir") + File.separator + "log" + File.separator + "chrome.log");
		
		HashMap<String, Object> chromePrefs = new HashMap<String, Object>();
		chromePrefs.put("profile.default_content_settings.popups", 2);
		chromePrefs.put("profile.default_content_settings.javascript", 1);
		chromePrefs.put("download.default_directory", path);
		chromePrefs.put("credentials_enable_service",false);
		chromePrefs.put("download.prompt_for_download", false);
		chromePrefs.put("profile.content_settings.exceptions.automatic_downloads.*.setting", 1);
		chromePrefs.put("safebrowsing.enabled", true);

		ChromeOptions options = new ChromeOptions();
		options.setExperimentalOption("excludeSwitches", new String[] { "enable-automation" });
		options.setExperimentalOption("forceDevToolsScreenshot", true);
        options.setExperimentalOption("useAutomationExtension", false);
        options.setExperimentalOption("detach", false);
		options.setExperimentalOption("prefs", chromePrefs);
		
		options.setCapability(CapabilityType.ACCEPT_SSL_CERTS, true);
		options.setCapability("enableVNC", true);
		options.setCapability("version", "67.0");
		
		options.addArguments("--disable-infobars"); 
        options.addArguments("--test-type"); 
        options.addArguments("--disable-extensions");
		options.addArguments("--ignore-certificate-errors");
		options.addArguments("--enable-javascript");
		options.addArguments("--start-maximized", "--window-size=1360,1020");

**Comment by vania-pooh** [comment] 2019-05-15 09:17
Duplicate of aerokube/selenoid#730.

**Closed by vania-pooh** 2019-05-15 09:17 UTC
